### ISSUE TITLE
Test issue for label switching and closing

### ISSUE THREAD

**Issue by ymnikhil** [nikhilym/MaGiRC-Test#5]
This is a test issue. Please ignore.

**Comment by ymnikhil** [comment]
Ok, so what should be done?

**Comment by nikhilym** [comment]
Essentially closed using a scheduler. Look out for the current time : 10.20 AM. Should be closed in around 5-10 minutes.

**Comment by nikhilym** [comment]
Essentially closed using a scheduler. Look out for the current time : 10.20 AM. Should be closed in around 5-10 minutes. Checking also that this comment won't remove the label.
